"""m3_rename_department

Revision ID: 2c212f2eab71
Revises: c9ee9996dc88
Create Date: 2026-04-24 12:55:56.639774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c212f2eab71'
down_revision = 'c9ee9996dc88'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ### 