"""m4_rename_address

Revision ID: 4cfaf2e98114
Revises: 2c212f2eab71
Create Date: 2026-04-24 13:03:05.991477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfaf2e98114'
down_revision = '2c212f2eab71'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ### 
